### Create admin note
POST localhost:8080/api/v1/notes
Authorization: Basic admin admin
Content-Type: application/json

{
  "title": "Admin Note",
  "content": "This note is created by an admin user."
}

### Try accesing admin note as workflow user FIXME: SHOULD FAIL BUT SHOWS ADMIN NOTE
GET localhost:8080/api/v1/notes?title=Admin%20Note
Authorization: Basic workflow-user workflow-user

